---
title: Ash's Portfolio
author: 'Ash '
email: ash.palmer@cryptmin.net
description: Portfilio of CNC, CAD, CAM, and Linux
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
